### ISSUE TITLE
Formatter to support not splitting array in a paren expression 

### ISSUE THREAD

**Issue by Hiryu52** [jlchmura/prettier-lpc-vscode#32]
Add to recognize arrays using syntax (({ }}) and not to split formatting.

Example:

items = (({
  "item", "Desc.\n",
}));

Gets changed to:
items =
  (
    ({
       "item",
       "Desc.\n",
    })
  );

**Comment by jlchmura** [comment]
This is by design. If your first array element is on a separate line from the array opening brackets, the formatter will go into "multiline" mode and space everything out vertically.  As long as the first element is on the same line, it will collapse everything like you're looking for. 

Example:
```c
test() {
    items = (
        ({"item", 
        "Desc.\n",
        }));
}
```
will generate:
```c
test() {
  items = (({"item", "Desc.\n"}));
}
```
